In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

Trian

In [ ]:
data = pd.read_csv('/content/train.csv')

In [ ]:
data

jobType       degree  ... milesFromMetropolis salary
0                  CFO      MASTERS  ...                  83    130
1                  CEO  HIGH_SCHOOL  ...                  73    101
2       VICE_PRESIDENT     DOCTORAL  ...                  38    137
3              MANAGER     DOCTORAL  ...                  17    142
4       VICE_PRESIDENT    BACHELORS  ...                  16    163
...                ...          ...  ...                 ...    ...
999990  VICE_PRESIDENT    BACHELORS  ...                  94     88
999991             CTO  HIGH_SCHOOL  ...                  35    160
999992          JUNIOR  HIGH_SCHOOL  ...                  81     64
999993             CFO      MASTERS  ...                   5    149
999994          JUNIOR    BACHELORS  ...                  11     88

[999995 rows x 7 columns]

In [ ]:
pd.Categorical(data['major'])

['MATH', 'NONE', 'PHYSICS', 'CHEMISTRY', 'PHYSICS', ..., 'CHEMISTRY', 'NONE', 'NONE', 'NONE', 'NONE']
Length: 999995
Categories (9, object): ['BIOLOGY', 'BUSINESS', 'CHEMISTRY', 'COMPSCI', ..., 'LITERATURE', 'MATH',
                         'NONE', 'PHYSICS']

In [ ]:
data.sample()

jobType degree major  ... yearsExperience  milesFromMetropolis  salary
269057     CTO   NONE  NONE  ...              13                   23     135

[1 rows x 7 columns]

In [ ]:
Category = ['jobType','degree','major','industry']
Num = ['yearsExperience','milesFromMetropolis']
label_encoder = LabelEncoder()
one_hot_encoder = OneHotEncoder()
EncodedCategoryColumns = []
for c in Category:
    label_encoder.fit(data[c])
    label_encoded = label_encoder.transform(data[c])
    label_encoded = label_encoded.reshape(len(label_encoded),1)
    encoded = one_hot_encoder.fit_transform(label_encoded).toarray()
    EncodedCategoryColumns.append(encoded)
Numfeature = data[Num].values
y_train = data['salary'].values
y_train = y_train.reshape(len(y_train),1)

X_train = np.append(EncodedCategoryColumns[0],EncodedCategoryColumns[1],axis=1)
X_train = np.append(X_train,EncodedCategoryColumns[2],axis=1)
X_train = np.append(X_train,EncodedCategoryColumns[3],axis=1)
X_train = np.append(X_train,Numfeature,axis=1)

#random split
X_train,X_test,y_train,y_test = train_test_split(X_train,y_train,test_size=0.2)

In [ ]:
np.shape(y_train)

(799996, 1)

In [ ]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(X_train,y_train)

LinearRegression()

SAVE

In [ ]:
import pickle
pickle.dump(LR, open('modelb.pkl','wb'))

Training Error

In [ ]:
print(LR.predict(X_train))

[[125.26355743]
 [102.96943665]
 [ 77.42057037]
 ...
 [ 62.31502533]
 [129.08094025]
 [130.44480896]]


In [ ]:
y_train

array([[129],
       [ 94],
       [ 66],
       ...,
       [ 70],
       [ 98],
       [161]])

Testing Error

In [ ]:
print(LR.predict(X_test))

[[ 89.40138245]
 [ 68.48504639]
 [187.75462341]
 ...
 [ 88.7043457 ]
 [107.71725464]
 [127.81959534]]


In [ ]:
y_test

array([[100],
       [110],
       [121],
       ...,
       [103],
       [127],
       [104]])

In [ ]:
pred = LR.predict(X_test)
temp = np.linalg.norm(pred-y_test,ord=1)
error = temp/(np.sum(y_test))

In [ ]:
(1-error)

0.863658584746559

YuqinEncoder

In [ ]:
def YuqinEncoder(Input):
    if Input[0] == 'CEO':
        Encoded0 = np.array([[1.,0.,0.,0.,0.,0.,0.,0.]])
    if Input[0] == 'CFO':
        Encoded0 = np.array([[0.,1.,0.,0.,0.,0.,0.,0.]])
    if Input[0] == 'CTO':
        Encoded0 = np.array([[0.,0.,1.,0.,0.,0.,0.,0.]])
    if Input[0] == 'JANITOR':
        Encoded0 = np.array([[0.,0.,0.,1.,0.,0.,0.,0.]])
    if Input[0] == 'JUNIOR':
        Encoded0 = np.array([[0.,0.,0.,0.,1.,0.,0.,0.]])
    if Input[0] == 'MANAGER':
        Encoded0 = np.array([[0.,0.,0.,0.,0.,1.,0.,0.]])
    if Input[0] == 'SENIOR':
        Encoded0 = np.array([[0.,0.,0.,0.,0.,0.,1.,0.]])
    if Input[0] == 'VICE_PRESIDENT':
        Encoded0 = np.array([[0.,0.,0.,0.,0.,0.,0.,1.]])

    if Input[1] == 'BACHELORS':
        Encoded1 = np.array([[1.,0.,0.,0.,0.]])
    if Input[1] == 'DOCTORAL':
        Encoded1 = np.array([[0.,1.,0.,0.,0.]])
    if Input[1] == 'HIGH_SCHOOL':
        Encoded1 = np.array([[0.,0.,1.,0.,0.]])
    if Input[1] == 'MASTERS':
        Encoded1 = np.array([[0.,0.,0.,1.,0.]])
    if Input[1] == 'NONE':
        Encoded1 = np.array([[0.,0.,0.,0.,1.]])

    if Input[2] == 'BIOLOGY':
        Encoded2 = np.array([[1.,0.,0.,0.,0.,0.,0.,0.,0.]])
    if Input[2] == 'BUSINESS':
        Encoded2 = np.array([[0.,1.,0.,0.,0.,0.,0.,0.,0.]])
    if Input[2] == 'CHEMISTRY':
        Encoded2 = np.array([[0.,0.,1.,0.,0.,0.,0.,0.,0.]])
    if Input[2] == 'COMPSCI':
        Encoded2 = np.array([[0.,0.,0.,1.,0.,0.,0.,0.,0.]])
    if Input[2] == 'ENGINEERING':
        Encoded2 = np.array([[0.,0.,0.,0.,1.,0.,0.,0.,0.]])
    if Input[2] == 'LITERATURE':
        Encoded2 = np.array([[0.,0.,0.,0.,0.,1.,0.,0.,0.]])
    if Input[2] == 'MATH':
        Encoded2 = np.array([[0.,0.,0.,0.,0.,0.,1.,0.,0.]])
    if Input[2] == 'NONE':
        Encoded2 = np.array([[0.,0.,0.,0.,0.,0.,0.,1.,0.]])
    if Input[2] == 'PHYSICS':
        Encoded2 = np.array([[0.,0.,0.,0.,0.,0.,0.,0.,1.]])

    if Input[3] == 'AUTO':
        Encoded3 = np.array([[1.,0.,0.,0.,0.,0.,0.]])
    if Input[3] == 'EDUCATION':
        Encoded3 = np.array([[0.,1.,0.,0.,0.,0.,0.]])
    if Input[3] == 'FINANCE':
        Encoded3 = np.array([[0.,0.,1.,0.,0.,0.,0.]])
    if Input[3] == 'HEALTH':
        Encoded3 = np.array([[0.,0.,0.,1.,0.,0.,0.]])
    if Input[3] == 'OIL':
        Encoded3 = np.array([[0.,0.,0.,0.,1.,0.,0.]])
    if Input[3] == 'SERVICE':
        Encoded3 = np.array([[0.,0.,0.,0.,0.,1.,0.]])
    if Input[3] == 'WEB':
        Encoded3 = np.array([[0.,0.,0.,0.,0.,0.,1.]])

    EncodedInput = np.append(Encoded0,Encoded1,axis=1)
    EncodedInput = np.append(EncodedInput,Encoded2,axis=1)
    EncodedInput = np.append(EncodedInput,Encoded3,axis=1)
    EncodedInput = np.append(EncodedInput,np.array([[Input[4]]]),axis=1)
    EncodedInput = np.append(EncodedInput,np.array([[Input[5]]]),axis=1)
    
    return EncodedInput

In [ ]:
Input = ['SENIOR','DOCTORAL','MATH','FINANCE',1000,0]
EncodedInput = YuqinEncoder(Input)

In [ ]:
LR.predict(EncodedInput)

array([[2141.70835876]])

LOAD

In [ ]:
model = pickle.load(open('modelb.pkl','rb'))
Input = ['JUNIOR','MASTERS','COMPSCI','WEB',10,20]
EncodedInput = YuqinEncoder(Input)
model.predict(EncodedInput)

array([[128.45803833]])

In [ ]:
x='3'
temp=[x]
print(temp)

['3']
